/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as ProblemRouteImport } from './routes/problem'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContestRouteImport } from './routes/contest'
import { Route as IndexRouteImport } from './routes/index'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemRoute = ProblemRouteImport.update({
  id: '/problem',
  path: '/problem',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestRoute = ContestRouteImport.update({
  id: '/contest',
  path: '/contest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contest': typeof ContestRoute
  '/dashboard': typeof DashboardRoute
  '/problem': typeof ProblemRoute
  '/problems': typeof ProblemsRoute
  '/teacher': typeof TeacherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contest': typeof ContestRoute
  '/dashboard': typeof DashboardRoute
  '/problem': typeof ProblemRoute
  '/problems': typeof ProblemsRoute
  '/teacher': typeof TeacherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contest': typeof ContestRoute
  '/dashboard': typeof DashboardRoute
  '/problem': typeof ProblemRoute
  '/problems': typeof ProblemsRoute
  '/teacher': typeof TeacherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contest'
    | '/dashboard'
    | '/problem'
    | '/problems'
    | '/teacher'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contest' | '/dashboard' | '/problem' | '/problems' | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/contest'
    | '/dashboard'
    | '/problem'
    | '/problems'
    | '/teacher'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContestRoute: typeof ContestRoute
  DashboardRoute: typeof DashboardRoute
  ProblemRoute: typeof ProblemRoute
  ProblemsRoute: typeof ProblemsRoute
  TeacherRoute: typeof TeacherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem': {
      id: '/problem'
      path: '/problem'
      fullPath: '/problem'
      preLoaderRoute: typeof ProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest': {
      id: '/contest'
      path: '/contest'
      fullPath: '/contest'
      preLoaderRoute: typeof ContestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContestRoute: ContestRoute,
  DashboardRoute: DashboardRoute,
  ProblemRoute: ProblemRoute,
  ProblemsRoute: ProblemsRoute,
  TeacherRoute: TeacherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
